version: '3.4'

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: ${USER_DB}
            POSTGRES_PASSWORD: ${PASSWORD_DB}
            POSTGRES_DB: ${NAME_DB}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - database_data:/var/lib/postgresql/data
        command: -p ${PORT_DB}
        ports:
            - "${PORT_DB}:${PORT_DB}"

    pg-admin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "postgres@email.com"
            PGADMIN_DEFAULT_PASSWORD: "postgres"
        ports:
            - "8080:80"
        depends_on:
            - postgres

volumes:
    database_data:
